import numpy as np
import matplotlib.pylab as plt

datax1 = np.genfromtxt("datax1.dat",delimiter=",")
datay1 = np.genfromtxt("datay1.dat",delimiter=",")
datax2 = np.genfromtxt("datax2.dat",delimiter=",")
datay2 = np.genfromtxt("datay2.dat",delimiter=",")
datax3 = np.genfromtxt("datax3.dat",delimiter=",")
datay3 = np.genfromtxt("datay3.dat",delimiter=",")
m_earth = 3.00273e-6

fig = plt.figure(figsize=(20,5))
a = fig.add_subplot(1,3,1)
a.plot(datax1[:,1],datay1[:,1],color="darkorange",label="dt = 0.1")
a.set_xlabel(u"Posición x.")
a.set_ylabel(u"Posición y.")
a.set_title(u"Rugen-Kutta: Posición en y vs. posición en x.")
a.legend()

b = fig.add_subplot(1,3,2)
b.plot(datax2[:,1],datay2[:,1],color="darkorange",label="dt = 0.001")
b.set_xlabel(u"Posición x.")
b.set_ylabel(u"Posición y.")
b.set_title(u"Rugen-Kutta: Posición en y vs. posición en x.")
b.legend()

c = fig.add_subplot(1,3,3)
c.plot(datax3[:,1],datay3[:,1],color="darkorange",label="dt = 0.0001")
c.set_xlabel(u"Posición x.")
c.set_ylabel(u"Posición y.")
c.set_title(u"Rugen-Kutta: Posición en y vs. posición en x.")
c.legend()

fig1 = plt.figure(figsize=(20,5))
a1 = fig1.add_subplot(1,3,1)
a1.plot(datax1[:,2],datay1[:,2],color="c",label="dt = 0.1")
a1.set_xlabel(u"Velocidad en x.")
a1.set_ylabel(u"Velocidad en y.")
a1.set_title(u"Rugen-Kutta: Velocidad en y vs. velocidad en x.")
a1.legend()

b1 = fig1.add_subplot(1,3,2)
b1.plot(datax2[:,2],datay2[:,2],color="c",label="dt = 0.001")
b1.set_xlabel(u"Velocidad en x.")
b1.set_ylabel(u"Velocidad en y.")
b1.set_title(u"Rugen-Kutta: Velocidad en y vs. velocidad en x.")
b1.legend()

c1 = fig1.add_subplot(1,3,3)
c1.plot(datax3[:,2],datay3[:,2],color="c",label="dt = 0.0001")
c1.set_xlabel(u"Velocidad en x.")
c1.set_ylabel(u"Velocidad en y.")
c1.set_title(u"Rugen-Kutta: Velocidad en y vs. velocidad en x.")
c1.legend()

fig2 = plt.figure(figsize=(20,5))
a2 = fig2.add_subplot(1,3,1)
a2.plot(datax1[:,0],datay1[:,2],m_earth*datax1[:,2]),color="indigo",label="dt = 0.1")
a2.set_xlabel(u"Velocidad en x.")
a2.set_ylabel(u"Velocidad en y.")
a2.set_title(u"Rugen-Kutta: Velocidad en y vs. velocidad en x.")
a2.legend()

b2 = fig2.add_subplot(1,3,2)
b2.plot(datax2[:,2],datay2[:,2],color="indigo",label="dt = 0.001")
b2.set_xlabel(u"Velocidad en x.")
b2.set_ylabel(u"Velocidad en y.")
b2.set_title(u"Rugen-Kutta: Velocidad en y vs. velocidad en x.")
b2.legend()

c2 = fig2.add_subplot(1,3,3)
c2.plot(datax3[:,2],datay3[:,2],color="indigo",label="dt = 0.0001")
c2.set_xlabel(u"Velocidad en x.")
c2.set_ylabel(u"Velocidad en y.")
c2.set_title(u"Rugen-Kutta: Velocidad en y vs. velocidad en x.")
c2.legend()
